<?php
/**
 * Loads the plugin's compiled frontend assets.
 *
 * @package Balw\BalwPlugin
 */

declare(strict_types=1);

namespace Balw\BalwPlugin;

use Balw\BalwPlugin\Interfaces\RegistersHooks;

/**
 * Enqueues the compiled frontend entry with its generated asset metadata.
 */
final class AssetLoader implements RegistersHooks {
	/**
	 * Absolute path to the plugin bootstrap file.
	 *
	 * @var string
	 */
	private string $plugin_file;

	/**
	 * Sets the plugin file used to resolve asset paths and URLs.
	 *
	 * @param string $plugin_file Absolute path to the plugin bootstrap file.
	 */
	public function __construct( string $plugin_file ) {
		$this->plugin_file = $plugin_file;
	}

	/**
	 * Attaches the frontend entry to WordPress script enqueueing.
	 */
	public function register_hooks(): void {
		add_action( 'wp_enqueue_scripts', [ $this, 'enqueue' ] );
	}

	/**
	 * Enqueues the frontend script when its build and metadata are available.
	 */
	public function enqueue(): void {
		$script_path = 'build/frontend/index.js';
		$asset_path  = dirname( $this->plugin_file ) . '/build/frontend/index.asset.php';

		if ( ! is_readable( dirname( $this->plugin_file ) . '/' . $script_path ) || ! is_readable( $asset_path ) ) {
			return;
		}

		/**
		 * Asset metadata generated by WordPress Scripts.
		 *
		 * @var array{dependencies: list<non-empty-string>, version: string} $asset
		 */
		$asset = require $asset_path;

		wp_enqueue_script(
			'balw-plugin-frontend',
			plugins_url( $script_path, $this->plugin_file ),
			$asset['dependencies'],
			$asset['version'],
			true
		);
	}
}
